### ISSUE TITLE
renderers not saving form data in 3.0.0

### ISSUE THREAD

**Issue by arksnorman** [ConnectForLife/openmrs-module-callflows#1]
I installed the new version 3.0.0 but unfortunately, when I would try to add a new renderer, a blank renderer would be returned after saving.

See the link below
https://imgur.com/FEPBXn8

**Comment by pwargulak** [comment]
Hi @arksnorman 

We are looking into it, unfortunately the only workaround is to edit the configuration files manually in web application docker in _/usr/local/tomcat/.OpenMRS/cf_config/callflows-settings.json_

`{"configs":[],"renderers":[{"name":"Renderer1","mimeType":"application/xml","template":"<xml />"}]}`

**Comment by pgesek** [comment]
We have moved this repository to: https://github.com/johnsonandjohnson/openmrs-module-callflows

If the issue still persists, please create it again in that repository. Sorry for the inconvenience.

Regards,
Paweł
